### ISSUE TITLE
用ilruntime，在hotfix.dll里注册的服务，不能实例化

### ISSUE THREAD

**Issue by fatfatson** [CatLib/Core#123]
```
 CatLib.App.Bind("ITestILR", typeof(TestILR), true);
 (CatLib.App.Make("ITestILR") as API.ITestILR).MakeLove("lbb");
```

ITestILR和TestILR都在hotfix.dll里，注册成功，但实例化失败：

> MissingMethodException: Default constructor not found for type ILRuntime.Runtime.Intepreter.ILTypeInstance at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x0007b] in <f2e6809acb14476a81f399aeb800f8f2>:0 at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <f2e6809acb14476a81f399aeb800f8f2>:0 at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <f2e6809acb14476a81f399aeb800f8f2>:0 at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x0002c] in <f2e6809acb14476a81f399aeb800f8f2>:0

**Comment by yb199478** [comment]
参考：
https://github.com/CatLib/demo-how-to-use-catlib-for-ilruntime
