### ISSUE TITLE
LogicException: The Application does not created, please call new Application() first.

### ISSUE THREAD

**Issue by panshengneng** [CatLib/Core#171]
Log日志：
LogicException: The Application does not created, please call new Application() first.
CatLib.App.get_Handler () (at Assets/CatLib/Vendor/CatLib.Core/CatLib/App.cs:60)
CatLib.App.Call (System.Object instance, System.Reflection.MethodInfo methodInfo, System.Object[] userParams) (at Assets/CatLib/Vendor/CatLib.Core/CatLib/App.cs:585)
CatLib.CatLibDispatcherExtend+<>c__DisplayClass1_0.<On>b__0 (System.String _, System.Object[] userParams) (at Assets/CatLib/Vendor/CatLib.Core/CatLib/Events/DispatcherExtend.cs:60)
CatLib.Dispatcher+<>c__DisplayClass13_0.<MakeListener>b__0 (System.String eventName, System.Object[] payloads) (at Assets/CatLib/Vendor/CatLib.Core/Support/Events/Dispatcher.cs:211)
CatLib.Event.Call (System.String eventName, System.Object[] payloads) (at Assets/CatLib/Vendor/CatLib.Core/Support/Events/Event.cs:57)
CatLib.Dispatcher.Dispatch (System.Boolean halt, System.String eventName, System.Object[] payload) (at Assets/CatLib/Vendor/CatLib.Core/Support/Events/Dispatcher.cs:254)
CatLib.Dispatcher.Trigger (System.String eventName, System.Object[] payloads) (at Assets/CatLib/Vendor/CatLib.Core/Support/Events/Dispatcher.cs:104)
CatLib.Application.Trigger (System.String eventName, System.Object[] payloads) (at Assets/CatLib/Vendor/CatLib.Core/CatLib/Application.cs:447)
CatLib.Application.Terminate () (at Assets/CatLib/Vendor/CatLib.Core/CatLib/Application.cs:199)
CatLib.Framework.OnDestroy () (at Assets/CatLib/Framework.cs:183)

出现过程：
1、创建一个新的Unity工程；
2、导入catlib-getstarting-1.3.0-beta.unitypackage和catlib-framework-1.3.0-beta.unitypackage；
3、创建一个新的GameObject，把Main.cs拖到新创建的GameObject上。 运行正常。
4、把Assets/CatLib/Vendor/CatLib.Core文件夹下的DLL，替换为https://github.com/CatLib/Core/src/CatLib.Core源码。运行，停止，看到上面报错日志。

开发环境：
macOS 10.14.2;
Unity 2018.3.0 f3;

Demo链接：
https://pan.baidu.com/s/1vu-uHQzwjdbYG1jYgQ-UoA

**Comment by panshengneng** [comment]
[CatLib_Test.zip](https://github.com/CatLib/Core/files/2737177/CatLib_Test.zip)

**Comment by yb199478** [comment]
问题已经确定, v1.3.1版本修复
