### ISSUE TITLE
[BUG] Spelling error on OnBootStrapped

### ISSUE THREAD

**Issue by GarfieldJiang** [CatLib/Core#209]
In both docs and source code, OnBootStrapped event is misspelled as OnBootStraped.

**Comment by yb199478** [comment]
This is a spelling mistake, but due to compatibility issues we may only be able to remove the old naming in version 2.0.

**Comment by yb199478** [comment]
Might we can choose some more specific words to describe this behavior, like: `OnAfterBooting`

**Comment by xixiko** [comment]
I think `OnAfterBooting` is the better.

**Comment by GarfieldJiang** [comment]
`OnAfterBoot` will be fine.

**Comment by yb199478** [comment]
This problem has been handled by a new approach. In 2.0, our event trigger will be changed to:

```csharp
eventSystem.On<AfterBootEventArgs>((eventArgs) => {
    // todo: 
});
```

We can also name it `EventArgsAfterBoot` . This way the IDE can combine events to display events together: 

```csharp
eventSystem.On<EventArgsAfterBoot>((eventArgs) => {
    // todo: 
});
```

**Comment by yb199478** [comment]
The issue is already being processed in submission #238.
