### ISSUE TITLE
[Naming suggestion] Framework events could be named better.

### ISSUE THREAD

**Issue by GarfieldJiang** [CatLib/Core#240]
There are widely used events for before doing something, on doing something and after doing something. You could use OnPreXXX, OnXXX and OnPostXXX for better readability, where XXX is a verb stem.

Example, when resolving a name, the 3 events could be named as:
- OnPreResolve,
- OnResolve, and
- OnPostResolve.

‘Event groups’ with only 1 or 2 events can also follow this convention.

**Comment by yb199478** [comment]
For what reason, use `post` instead of `after`, like:

- OnResolving
- OnAfterResolving

**Comment by GarfieldJiang** [comment]
Shorter. :)

At least you don't need the -ing suffix.

**Comment by yb199478** [comment]
Using `ing` is to indicate that the event is in progress.

**Comment by GarfieldJiang** [comment]
Yup, finally I understood why you named things as such.
